# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_binfile.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dlgBinFile(object):
    def setupUi(self, dlgBinFile):
        dlgBinFile.setObjectName("dlgBinFile")
        dlgBinFile.resize(692, 315)
        self.lblBt = QtWidgets.QLabel(dlgBinFile)
        self.lblBt.setGeometry(QtCore.QRect(20, 65, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lblBt.setFont(font)
        self.lblBt.setObjectName("lblBt")
        self.edtBtType = QtWidgets.QLineEdit(dlgBinFile)
        self.edtBtType.setGeometry(QtCore.QRect(145, 68, 431, 31))
        self.edtBtType.setObjectName("edtBtType")
        self.lbl_tips = QtWidgets.QLabel(dlgBinFile)
        self.lbl_tips.setGeometry(QtCore.QRect(22, 10, 551, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.lbl_tips.setFont(font)
        self.lbl_tips.setObjectName("lbl_tips")
        self.btnBtType = QtWidgets.QPushButton(dlgBinFile)
        self.btnBtType.setGeometry(QtCore.QRect(596, 69, 71, 28))
        self.btnBtType.setObjectName("btnBtType")
        self.lblVoice = QtWidgets.QLabel(dlgBinFile)
        self.lblVoice.setGeometry(QtCore.QRect(16, 127, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lblVoice.setFont(font)
        self.lblVoice.setObjectName("lblVoice")
        self.btnVoiceType = QtWidgets.QPushButton(dlgBinFile)
        self.btnVoiceType.setGeometry(QtCore.QRect(595, 134, 71, 28))
        self.btnVoiceType.setObjectName("btnVoiceType")
        self.edtVoiceType = QtWidgets.QLineEdit(dlgBinFile)
        self.edtVoiceType.setGeometry(QtCore.QRect(144, 133, 431, 31))
        self.edtVoiceType.setObjectName("edtVoiceType")
        self.btnDemoType = QtWidgets.QPushButton(dlgBinFile)
        self.btnDemoType.setGeometry(QtCore.QRect(595, 199, 71, 28))
        self.btnDemoType.setObjectName("btnDemoType")
        self.lblDemo = QtWidgets.QLabel(dlgBinFile)
        self.lblDemo.setGeometry(QtCore.QRect(16, 192, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lblDemo.setFont(font)
        self.lblDemo.setObjectName("lblDemo")
        self.edtDemoType = QtWidgets.QLineEdit(dlgBinFile)
        self.edtDemoType.setGeometry(QtCore.QRect(144, 198, 431, 31))
        self.edtDemoType.setObjectName("edtDemoType")
        self.btnOK = QtWidgets.QPushButton(dlgBinFile)
        self.btnOK.setGeometry(QtCore.QRect(214, 259, 93, 28))
        self.btnOK.setObjectName("btnOK")
        self.btnCancel = QtWidgets.QPushButton(dlgBinFile)
        self.btnCancel.setGeometry(QtCore.QRect(360, 260, 93, 28))
        self.btnCancel.setObjectName("btnCancel")

        self.retranslateUi(dlgBinFile)
        QtCore.QMetaObject.connectSlotsByName(dlgBinFile)

    def retranslateUi(self, dlgBinFile):
        _translate = QtCore.QCoreApplication.translate
        dlgBinFile.setWindowTitle(_translate("dlgBinFile", "固件文件选择"))
        self.lblBt.setText(_translate("dlgBinFile", "B T 类型:"))
        self.lbl_tips.setText(_translate("dlgBinFile", "请选择对应的文件类型(*.bin):"))
        self.btnBtType.setText(_translate("dlgBinFile", "..."))
        self.lblVoice.setText(_translate("dlgBinFile", "Voice 类型:"))
        self.btnVoiceType.setText(_translate("dlgBinFile", "..."))
        self.btnDemoType.setText(_translate("dlgBinFile", "..."))
        self.lblDemo.setText(_translate("dlgBinFile", "Demo 类型:"))
        self.btnOK.setText(_translate("dlgBinFile", "确定"))
        self.btnCancel.setText(_translate("dlgBinFile", "取消"))
