# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_help.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_diaHelp(object):
    def setupUi(self, diaHelp):
        diaHelp.setObjectName("diaHelp")
        diaHelp.resize(512, 311)
        self.lbl_sp_1 = QtWidgets.QLabel(diaHelp)
        self.lbl_sp_1.setGeometry(QtCore.QRect(40, 23, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lbl_sp_1.setFont(font)
        self.lbl_sp_1.setObjectName("lbl_sp_1")
        self.lbl_sp_2 = QtWidgets.QLabel(diaHelp)
        self.lbl_sp_2.setGeometry(QtCore.QRect(40, 56, 331, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lbl_sp_2.setFont(font)
        self.lbl_sp_2.setObjectName("lbl_sp_2")
        self.lbl_sp_3 = QtWidgets.QLabel(diaHelp)
        self.lbl_sp_3.setGeometry(QtCore.QRect(39, 90, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lbl_sp_3.setFont(font)
        self.lbl_sp_3.setObjectName("lbl_sp_3")
        self.lbl_tip_1 = QtWidgets.QLabel(diaHelp)
        self.lbl_tip_1.setGeometry(QtCore.QRect(20, 160, 481, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lbl_tip_1.setFont(font)
        self.lbl_tip_1.setObjectName("lbl_tip_1")
        self.lbl_tip_2 = QtWidgets.QLabel(diaHelp)
        self.lbl_tip_2.setGeometry(QtCore.QRect(43, 185, 451, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lbl_tip_2.setFont(font)
        self.lbl_tip_2.setObjectName("lbl_tip_2")
        self.btnOK = QtWidgets.QPushButton(diaHelp)
        self.btnOK.setGeometry(QtCore.QRect(216, 266, 93, 28))
        self.btnOK.setObjectName("btnOK")
        self.lblLogo = QtWidgets.QLabel(diaHelp)
        self.lblLogo.setGeometry(QtCore.QRect(383, 38, 72, 61))
        self.lblLogo.setObjectName("lblLogo")
        self.lbl_sp_4 = QtWidgets.QLabel(diaHelp)
        self.lbl_sp_4.setGeometry(QtCore.QRect(39, 124, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lbl_sp_4.setFont(font)
        self.lbl_sp_4.setObjectName("lbl_sp_4")
        self.lbl_tip_3 = QtWidgets.QLabel(diaHelp)
        self.lbl_tip_3.setGeometry(QtCore.QRect(43, 206, 451, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lbl_tip_3.setFont(font)
        self.lbl_tip_3.setObjectName("lbl_tip_3")
        self.lbl_tip_4 = QtWidgets.QLabel(diaHelp)
        self.lbl_tip_4.setGeometry(QtCore.QRect(43, 229, 441, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lbl_tip_4.setFont(font)
        self.lbl_tip_4.setObjectName("lbl_tip_4")

        self.retranslateUi(diaHelp)
        QtCore.QMetaObject.connectSlotsByName(diaHelp)

    def retranslateUi(self, diaHelp):
        _translate = QtCore.QCoreApplication.translate
        diaHelp.setWindowTitle(_translate("diaHelp", "使用帮助"))
        self.lbl_sp_1.setText(_translate("diaHelp", "1:选择->配置->串口类型"))
        self.lbl_sp_2.setText(_translate("diaHelp", "2:选择->配置->选择文件"))
        self.lbl_sp_3.setText(_translate("diaHelp", "3:选择->协议->C模块协议"))
        self.lbl_tip_1.setText(_translate("diaHelp", "注: 1.C模块协议升级比Python协议要快数分钟"))
        self.lbl_tip_2.setText(_translate("diaHelp", " 2.BT类型->选择对应的文件(BT_FW_*.bin)"))
        self.btnOK.setText(_translate("diaHelp", "确定"))
        self.lblLogo.setText(_translate("diaHelp", "TextLabel"))
        self.lbl_sp_4.setText(_translate("diaHelp", "4:选择->类型->要升级的文件类型"))
        self.lbl_tip_3.setText(_translate("diaHelp", " 3.Voice类型->选择对应的文件(Combined_*.bin)"))
        self.lbl_tip_4.setText(_translate("diaHelp", " 4.Demo类型->选择对应的文件(Demo_*.bin)"))
