# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_com.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialogCom(object):
    def setupUi(self, dialogCom):
        dialogCom.setObjectName("dialogCom")
        dialogCom.resize(467, 360)
        self.tableView = QtWidgets.QTableView(dialogCom)
        self.tableView.setGeometry(QtCore.QRect(4, 1, 451, 281))
        self.tableView.setObjectName("tableView")
        self.btnRefresh = QtWidgets.QPushButton(dialogCom)
        self.btnRefresh.setGeometry(QtCore.QRect(45, 310, 93, 28))
        self.btnRefresh.setObjectName("btnRefresh")
        self.btnOk = QtWidgets.QPushButton(dialogCom)
        self.btnOk.setGeometry(QtCore.QRect(172, 310, 93, 28))
        self.btnOk.setObjectName("btnOk")
        self.btnCancel = QtWidgets.QPushButton(dialogCom)
        self.btnCancel.setGeometry(QtCore.QRect(307, 310, 93, 28))
        self.btnCancel.setObjectName("btnCancel")

        self.retranslateUi(dialogCom)
        QtCore.QMetaObject.connectSlotsByName(dialogCom)

    def retranslateUi(self, dialogCom):
        _translate = QtCore.QCoreApplication.translate
        dialogCom.setWindowTitle(_translate("dialogCom", "Dialog"))
        self.btnRefresh.setText(_translate("dialogCom", "刷新"))
        self.btnOk.setText(_translate("dialogCom", "确定"))
        self.btnCancel.setText(_translate("dialogCom", "取消"))
